### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by aminbabar** [cjburchfield/pintwist#3]
# Database Schema

- [ ] Contains correct datatypes
- [x]  Contains appropriate constraints/details
    - [x]  primary key
    - [x]  not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
    - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

**Comment by aminbabar** [comment]
- missing right bracket on: "index on [:follower_id, :following_id, unique: true"
- You would want your descriptions to be type text. Type string is limited to 255 chars.

**Comment by cjburchfield** [comment]
> * missing right bracket on: "index on [:follower_id, :following_id, unique: true"
> * You would want your descriptions to be type text. Type string is limited to 255 chars.

Added the missing bracket and updated the descriptions to be type text, thank you @aminbabar
