### ISSUE TITLE
Frontend Routes

### ISSUE THREAD

**Issue by aminbabar** [cjburchfield/pintwist#6]
# Frontend Routes

- [x]  Frontend routes contains wildcard variables written in `camelCase`
- [x]  Correctly formatted
    - [x]  Routes are displayed with inline coding text (backticks)

**Comment by aminbabar** [comment]
- You do not need the /home route. That can be your / when you are logged in.
- it would also be okay to have a route of /users/:userId instead of /users/username, but I will leave that up to you

**Comment by cjburchfield** [comment]
> * You do not need the /home route. That can be your / when you are logged in.
> * it would also be okay to have a route of /users/:userId instead of /users/username, but I will leave that up to you

@aminbabar updated /home route, and leaving as /users/username for now as that's how Pinterest has it, but can discuss live if you think this would be an issue
